#!/bin/sh

set -e

cd ~/git
cd core-text-rs && git pull
cd ../core-graphics-rs && git pull
cd ../core-foundation-rs && git pull
cd ../webrender && git pull
cd ../webrender_traits && git pull
cd ../gleam && git pull
cd ../servo-webrender
git fetch glennw
git fetch servo
git checkout resources
git checkout master
git pull servo master
git branch -D webrender
git checkout -b webrender glennw/webrender
