#!/bin/sh

set -e

tmp_dir=`mktemp -d`
mkdir -p $tmp_dir/servo

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
$scriptdir/servo-tools-dist $@ $tmp_dir/servo

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  os=linux
elif [[ "$OSTYPE" == "darwin"* ]]; then
  os=mac
else
  os=unknown
fi

if  [[ $1 = "-r" ]]; then
  build=release
elif [[ $1 = "-d" ]]; then
  build=debug
fi

branch=`git rev-parse --abbrev-ref HEAD`
zip_name=servo-$build-$branch-$os-`date +"%Y-%m-%d"`.zip

cd $tmp_dir
zip -q -r $zip_name servo
cd -
cp $tmp_dir/$zip_name .
rm -rf $tmp_dir
