#!/bin/sh

set -e -x

if  [[ $1 = "-r" ]]; then
  build=release
elif [[ $1 = "-d" ]]; then
  build=debug
else
  echo "Error: use -r or -d to specifify the build type (release / debug)"
  exit
fi

rm -rf dist-$build
mkdir dist-$build
cp -r target/$build/deps target/$build/servo resources dist-$build
